package com.kashta.kala.ui.quotes

import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.lifecycle.lifecycleScope
import androidx.recyclerview.widget.LinearLayoutManager
import com.kashta.kala.KashtaApp
import com.kashta.kala.data.model.Quote
import com.kashta.kala.databinding.FragmentQuotesBinding
import kotlinx.coroutines.launch

class QuotesFragment : Fragment() {

    private var _binding: FragmentQuotesBinding? = null
    private val binding get() = _binding!!

    private lateinit var adapter: QuotesAdapter

    private val repository by lazy {
        (requireActivity().application as KashtaApp).repository
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentQuotesBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupRecyclerView()
        observeQuotes()
    }

    private fun setupRecyclerView() {
        adapter = QuotesAdapter(
            emptyList(),
            onDeleteClick = { quote -> deleteQuote(quote) },
            onShareClick = { quote -> shareQuote(quote) }
        )
        binding.rvQuotes.layoutManager = LinearLayoutManager(requireContext())
        binding.rvQuotes.adapter = adapter
    }

    private fun observeQuotes() {
        repository.allQuotes.observe(viewLifecycleOwner) { quotes ->
            if (quotes.isEmpty()) {
                binding.tvEmpty.visibility = View.VISIBLE
                binding.rvQuotes.visibility = View.GONE
            } else {
                binding.tvEmpty.visibility = View.GONE
                binding.rvQuotes.visibility = View.VISIBLE
                adapter.updateList(quotes)
            }
        }
    }

    private fun deleteQuote(quote: Quote) {
        lifecycleScope.launch {
            repository.deleteQuote(quote)
        }
    }

    private fun shareQuote(quote: Quote) {
        val message = """
            *Kashta-Kala Quote* 🪵
            
            Item: ${quote.itemName}
            Wood: ${quote.woodType}
            Dimensions: ${quote.length}×${quote.width}×${quote.height} ft
            
            Material Cost: ₹${"%.0f".format(quote.materialCost)}
            Labour Cost: ₹${"%.0f".format(quote.laborCost)}
            Extra Cost: ₹${"%.0f".format(quote.extraCost)}
            
            *Total: ₹${"%.0f".format(quote.totalCost)}*
            
            Date: ${quote.date}
            
            _Generated by Kashta-Kala App_
        """.trimIndent()

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, message)
        }
        startActivity(Intent.createChooser(intent, "Share Quote via"))
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}